// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknfHaF1_1TlP-se6-FZIqcbNs8GFdaMo',
    appId: '1:628797518380:web:fef62a775234bb8080d789',
    messagingSenderId: '628797518380',
    projectId: 'fruit-hup-218a8',
    authDomain: 'fruit-hup-218a8.firebaseapp.com',
    storageBucket: 'fruit-hup-218a8.firebasestorage.app',
    measurementId: 'G-Z2MZT0EN55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyokVhMnA_CZCTPA-AwF4dCUFCOvN0P7Q',
    appId: '1:628797518380:android:a7144aa7ede3f9ca80d789',
    messagingSenderId: '628797518380',
    projectId: 'fruit-hup-218a8',
    storageBucket: 'fruit-hup-218a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTdztujcG9iQ7colGyXry4zYQCvhQ_qE',
    appId: '1:628797518380:ios:f7c2f448da18cc8180d789',
    messagingSenderId: '628797518380',
    projectId: 'fruit-hup-218a8',
    storageBucket: 'fruit-hup-218a8.firebasestorage.app',
    iosBundleId: 'com.example.fruitECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrTdztujcG9iQ7colGyXry4zYQCvhQ_qE',
    appId: '1:628797518380:ios:f7c2f448da18cc8180d789',
    messagingSenderId: '628797518380',
    projectId: 'fruit-hup-218a8',
    storageBucket: 'fruit-hup-218a8.firebasestorage.app',
    iosBundleId: 'com.example.fruitECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCknfHaF1_1TlP-se6-FZIqcbNs8GFdaMo',
    appId: '1:628797518380:web:88107df3d4e06ef180d789',
    messagingSenderId: '628797518380',
    projectId: 'fruit-hup-218a8',
    authDomain: 'fruit-hup-218a8.firebaseapp.com',
    storageBucket: 'fruit-hup-218a8.firebasestorage.app',
    measurementId: 'G-L77KL0WVG1',
  );
}
