// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXx4Uqf2w-QYBXLy523QRcrgcS7bF3UA8',
    appId: '1:589012893254:web:36d509be02038fc6155447',
    messagingSenderId: '589012893254',
    projectId: 'fruit-e-commerce-572db',
    authDomain: 'fruit-e-commerce-572db.firebaseapp.com',
    storageBucket: 'fruit-e-commerce-572db.firebasestorage.app',
    measurementId: 'G-251KFNTFHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWyxTpWjsmw9RcUQon-Rb79cq2HA-yHTk',
    appId: '1:589012893254:android:76e1999990cf2535155447',
    messagingSenderId: '589012893254',
    projectId: 'fruit-e-commerce-572db',
    storageBucket: 'fruit-e-commerce-572db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4V5lAN93rti89U1AeJK5M9HceZfZIrA',
    appId: '1:589012893254:ios:dd1a49727cd6f303155447',
    messagingSenderId: '589012893254',
    projectId: 'fruit-e-commerce-572db',
    storageBucket: 'fruit-e-commerce-572db.firebasestorage.app',
    iosBundleId: 'com.example.fruitECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-4V5lAN93rti89U1AeJK5M9HceZfZIrA',
    appId: '1:589012893254:ios:dd1a49727cd6f303155447',
    messagingSenderId: '589012893254',
    projectId: 'fruit-e-commerce-572db',
    storageBucket: 'fruit-e-commerce-572db.firebasestorage.app',
    iosBundleId: 'com.example.fruitECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXx4Uqf2w-QYBXLy523QRcrgcS7bF3UA8',
    appId: '1:589012893254:web:03f3862b76db5d91155447',
    messagingSenderId: '589012893254',
    projectId: 'fruit-e-commerce-572db',
    authDomain: 'fruit-e-commerce-572db.firebaseapp.com',
    storageBucket: 'fruit-e-commerce-572db.firebasestorage.app',
    measurementId: 'G-F1WLLKSQFJ',
  );
}
